language: objective-c
osx_image: xcode10.1
dist: trusty

cache:
  directories:
  - vendor/bundle

before_script:
  - bundle exec danger

script:
  - swift --version
  - swift package update
  - swift test

branches:
  only:
  - master

notifications:
  slack:
    secure: vD4u2dU/iV8AD4ydOETi5SJ1ihvRf3LRtEgro1smh56X19x6wrL8Lt96Ky44yosrDM3tNCVUq2ZbICr6WpdkvdnquRS8HCkku3xTEXq9vCnn94kVZ4eT91ZkzvHbLKdGH+Lak/t4E6A9MpmzTMzM9VmiauAXh5bS7E2nvxgg+8belCELs2KNdecPUiooty/baVRDqhFJc83NdU5Q7Gj2+7PTSBCy2uSmwRjbUf9Kl0Hr+kRy/HR3bLsiljkkWbqfe95y1xSHfKbVfDIqRyqpRU6BjKbVJlmCuWasOLg0mksxwtnYxGa3DI4QozhoRadIN3gbtSuzAb/zfz5/duOaBbnR9YKYnCP4Okj35uPEipxCRuIAuIBH2teSW1fcHSWMxemL+QxwV87l0l1fJn7EMPeMKuFrBmcFvXt4Etjfg9hpKt7PXqF3TscxF90YrsLBr4utxMuV3mEXS0o616NoQ9FVXOTpFOLlOCcXm1qoTK1mWHv4wiZJF63CffNe5PEuIiK9l9tNEPCz1bJtzp+m9sfFlWotupUALQGBJtIgALgHEy+2V7F7RWX56UnMcU+tVKER28AXbOhATzo0O2wUCZIJU5PPAqyQdYMlnuY7rnwnkUYXHo538Q0gkk/ELkW2/UnT0Yf/cZYT4Gs/yZTzzqZxRUwViq6PswmmGgCFa/s=
